// Assembly PsdParser, Version 1.1.0.0

[assembly: System.Reflection.AssemblyVersion("1.1.0.0")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Resources.NeutralResourcesLanguage("en")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyTitle("PsdParser Class Library")]
[assembly: System.Reflection.AssemblyDescription("Class library is for extract PSD file layers")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyCompany("JeongHo Eom")]
[assembly: System.Reflection.AssemblyProduct("PsdParser.dll")]
[assembly: System.Reflection.AssemblyCopyright("Copyright ?2013 JeongHo Eom")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyDelaySign(false)]
[assembly: System.Reflection.AssemblyKeyFile("")]
[assembly: System.Reflection.AssemblyKeyName("")]
[assembly: System.Reflection.AssemblyFileVersion("1.1.0")]
[assembly: System.Runtime.InteropServices.Guid("9AA2926B-FCA5-420C-A233-C877E0508C56")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.RequestMinimum, SkipVerification=true)]

